### ISSUE TITLE
Display images as grid

### ISSUE THREAD

**Issue by gkssjovi** [atanunq/viu#85] opened 2021-11-23 09:43 UTC
Hi,

It is possible to display images in a grid table instead of one image per line?
For example when I git this command:
`viu . -w 20`

Kind Regard,
Ovidiu

**Comment by atanunq** [comment] 2021-11-23 10:42
Hey! Unfortunately, it's not possible. The functionality from `viuer` should be sufficient if one wants to implement it, though :)

Also, looks like a duplicate of https://github.com/atanunq/viu/issues/66

**Closed by atanunq** 2021-11-23 10:42 UTC

**Comment by gkssjovi** [comment] 2021-11-23 16:43
Ok, thank you.
I have tried to modify the function `print_buffer` from `viuer`. I have changed the writeln! to write! it is displayed on diagonal now ;)
